// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	telegram2 "github.com/farwydi/stickfinbot/internal/endpoint/telegram"
	"github.com/farwydi/stickfinbot/internal/gateway/telegram"
	"github.com/farwydi/stickfinbot/pkg/domain"
	"github.com/farwydi/stickfinbot/pkg/usecase/general"
)

// Injectors from bootstrap.go:

func bootstrap() (domain.Endpoint, func(), error) {
	telegramGateway, err := telegram.NewTelegramGateway()
	if err != nil {
		return nil, nil, err
	}
	generalGeneral := general.NewGeneralUseCase(telegramGateway)
	endpoint := telegram2.NewTelegramEndpoint(generalGeneral)
	return endpoint, func() {
	}, nil
}
